console.log ("javaScript".charAt(4));
console.log ("java".concat("","Script"));
console.log("javaScript".startsWith("H"));
console.log("javaScript".endsWith("i"));
console.log("javaScript".includes("h"));
console.log("javaScript".indexOf("i"));
console.log("javaScript".lastIndexOf("i"));
console.log("javaScript".match(/[A-Z]/g));
console.log("javaScript".padStart(7,"?"));
console.log("javaScript".padEnd(7,"?"));
console.log("javaScript".repeat("7"));
console.log("javaScript".replace("XOXO","?"));
console.log("javaScript".search("i"));
console.log("javaScript".slice(7,5));
console.log("javaScript".split(""));
console.log("javaScript".substring(7,5));
console.log("javaScript".toLocaleLowerCase(7,5));
console.log("javaScript".toUpperCase(7,5));
console.log("javaScript".trim());
console.log("javaScript".trimStart());
console.log("javaScript".trimEnd());